#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	DynaPage::Sourcer;
	
	print "START\n";
	
	my	$source		= qx( cat source1.txt );
	my	$s 		= new DynaPage::Sourcer( $source );	

	print "PARSED\n";
	
	print pp($s->Content())