#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	DynaPage::Sourcer;
	
	print "START\n";
	
	my	$source		= qx( cat source1.txt );
	my	$s 			= new DynaPage::Sourcer( $source );	

	print "PARSED\n";
	
	print 'sl1: ', scalar $s->Get( 'sl1', undef, '<br>' ), "\n";
	print 'sl2: ', scalar $s->Get( 'sl2', undef, '<br>' ), "\n";
