#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	DynaPage::Sourcer;
	
	print "START\n";
	
	my	$source		= qx( cat source1.txt );
	my	$s 			= new DynaPage::Sourcer();	

	$s->Parse( $source );
	print "-- source:\n", join( "\n", $s->NewNames(), '' ), "\n";
	
	$s->Parse( "new-name =- abc\n" );
	print "-- string:\n", join( "\n", $s->NewNames(), '' ), "\n";

	
